# ************************************************************************
# Product    : Home information and control
# Date       : 2016-12-28
# Copyright  : Copyright (C) 2016 Kjeholt Engineering. All rights reserved.
# Contact    : dev@kjeholt.se
# Url        : http://www-dev.kjeholt.se
# Licence    : ---
# -------------------------------------------------------------------------
# File       : mqtt-agent-tellstick/Dockerfile-rpi
# Version    : 1.0.0
# Author     : Bjorn Kjeholt
# *************************************************************************
 
FROM hypriot/rpi-node:latest

MAINTAINER Björn Kjeholt <dev@kjeholt.se>

RUN apt-get update
RUN apt-get install -y vim \
                       wget \
                       gcc \
                       cmake \
                       build-essential \
                       libconfuse-dev \
                       libftdi-dev \
                       help2man && \
    apt-get clean

RUN mkdir -p /usr/src/app && \
    mkdir -p /usr/src/app/js && \
    mkdir -p /usr/src/app/script

RUN npm install mqtt && \
    npm install jontelldus

# Add Telldus repository
RUN echo "deb-src http://download.telldus.com/debian/ stable main" >> /etc/apt/sources.list.d/telldus.list && \
    wget http://download.telldus.se/debian/telldus-public.key && \
    apt-key add telldus-public.key && \
    rm telldus-public.key

# Install dependencies. Compile and install telldusd
RUN apt-get update && \
    apt-get build-dep -y telldus-core && \
    apt-get --compile source telldus-core && \
    dpkg --install *.deb

# Install app dependencies
WORKDIR /usr/src/app

# Bundle app source
COPY js /usr/src/app/js
COPY Scripts /usr/src/app/script
COPY Configs /etc

RUN chmod 755 /usr/src/app/script/* && \
    chmod 755 /usr/src/app/*


ARG DOCKER_IMAGE_NAME
ARG DOCKER_IMAGE_TAG

ENV DOCKER_BASE_IMAGE_NAME na
ENV DOCKER_BASE_IMAGE_TAG na

ENV DOCKER_IMAGE_NAME ${DOCKER_IMAGE_NAME:-UnknownName}
ENV DOCKER_IMAGE_TAG ${DOCKER_IMAGE_TAG:-UnknownRevision}

WORKDIR /usr/src/app

CMD Scripts/execute.sh
